<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  
  <ItemGroup>
    <Content Include="assets\APMusic\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>assets\APMusic\%(RecursiveDir)\%(Filename)%(Extension)</Link>
      <TargetPath>APMusic\%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
    </Content>
    <Content Include="assets\BashLogs.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>lib\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Archipelago.MultiClient.Net">
      <HintPath>lib\Archipelago.MultiClient.Net.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>lib\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Hacknet">
      <HintPath>lib\BepInEx.Hacknet.dll</HintPath>
    </Reference>
    <Reference Include="FNA">
      <HintPath>lib\FNA.dll</HintPath>
    </Reference>
    <Reference Include="Hacknet">
      <HintPath>lib\Hacknet.exe</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>lib\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>lib\MonoMod.Utils.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>lib\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="PathfinderAPI">
      <HintPath>lib\PathfinderAPI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="ilrepack /lib:&quot;$(ProjectDir)lib/&quot; /out:&quot;$(TargetDir)$(TargetFileName)&quot; &quot;$(TargetDir)$(TargetFileName)&quot; &quot;$(TargetDir)Archipelago.MultiClient.Net.dll&quot; &amp;&amp; echo &quot;ILRepack finished, wahoo&quot;" />
  </Target>

</Project>
